In [224]:
import pandas as pd
import numpy as np


data = pd.read_csv(r"C:\Users\Sakthish Kumar\Downloads\TravelInsurancePrediction.csv")
data.head()

Unnamed: 0  Age               Employment Type GraduateOrNot  AnnualIncome  \
0           0   31             Government Sector           Yes        400000   
1           1   31  Private Sector/Self Employed           Yes       1250000   
2           2   34  Private Sector/Self Employed           Yes        500000   
3           3   28  Private Sector/Self Employed           Yes        700000   
4           4   28  Private Sector/Self Employed           Yes        700000   

   FamilyMembers  ChronicDiseases FrequentFlyer EverTravelledAbroad  \
0              6                1            No                  No   
1              7                0            No                  No   
2              4                1            No                  No   
3              3                1            No                  No   
4              8                1           Yes                  No   

   TravelInsurance  
0                0  
1                0  
2                1  
3                0  
4                0

In [225]:
data.shape

(1987, 10)

In [226]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1987 entries, 0 to 1986
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Unnamed: 0           1987 non-null   int64 
 1   Age                  1987 non-null   int64 
 2   Employment Type      1987 non-null   object
 3   GraduateOrNot        1987 non-null   object
 4   AnnualIncome         1987 non-null   int64 
 5   FamilyMembers        1987 non-null   int64 
 6   ChronicDiseases      1987 non-null   int64 
 7   FrequentFlyer        1987 non-null   object
 8   EverTravelledAbroad  1987 non-null   object
 9   TravelInsurance      1987 non-null   int64 
dtypes: int64(6), object(4)
memory usage: 155.4+ KB


In [227]:
data.isnull().sum()

Unnamed: 0             0
Age                    0
Employment Type        0
GraduateOrNot          0
AnnualIncome           0
FamilyMembers          0
ChronicDiseases        0
FrequentFlyer          0
EverTravelledAbroad    0
TravelInsurance        0
dtype: int64

In [228]:
correlation=data.corr()  # relationship between each column in dataset.

In [229]:
correlation

Unnamed: 0       Age  AnnualIncome  FamilyMembers  \
Unnamed: 0         1.000000 -0.004917     -0.025031      -0.041506   
Age               -0.004917  1.000000     -0.020101       0.027409   
AnnualIncome      -0.025031 -0.020101      1.000000      -0.015367   
FamilyMembers     -0.041506  0.027409     -0.015367       1.000000   
ChronicDiseases   -0.006858  0.007359     -0.001149       0.028209   
TravelInsurance    0.006196  0.061060      0.396763       0.079909   

                 ChronicDiseases  TravelInsurance  
Unnamed: 0             -0.006858         0.006196  
Age                     0.007359         0.061060  
AnnualIncome           -0.001149         0.396763  
FamilyMembers           0.028209         0.079909  
ChronicDiseases         1.000000         0.018190  
TravelInsurance         0.018190         1.000000

In [230]:
data.describe()

Unnamed: 0          Age  AnnualIncome  FamilyMembers  ChronicDiseases  \
count  1987.000000  1987.000000  1.987000e+03    1987.000000      1987.000000   
mean    993.000000    29.650226  9.327630e+05       4.752894         0.277806   
std     573.741812     2.913308  3.768557e+05       1.609650         0.448030   
min       0.000000    25.000000  3.000000e+05       2.000000         0.000000   
25%     496.500000    28.000000  6.000000e+05       4.000000         0.000000   
50%     993.000000    29.000000  9.000000e+05       5.000000         0.000000   
75%    1489.500000    32.000000  1.250000e+06       6.000000         1.000000   
max    1986.000000    35.000000  1.800000e+06       9.000000         1.000000   

       TravelInsurance  
count      1987.000000  
mean          0.357323  
std           0.479332  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           1.000000  
max           1.000000

In [231]:
data['TravelInsurance'].value_counts()

0    1277
1     710
Name: TravelInsurance, dtype: int64

In [232]:
data.groupby('TravelInsurance').mean()

Unnamed: 0        Age  AnnualIncome  FamilyMembers  \
TravelInsurance                                                       
0                990.350039  29.517619  8.212999e+05       4.657009   
1                997.766197  29.888732  1.133239e+06       4.925352   

                 ChronicDiseases  
TravelInsurance                   
0                       0.271731  
1                       0.288732

In [233]:
x=data.drop(columns=['TravelInsurance','Employment Type','GraduateOrNot','FrequentFlyer','EverTravelledAbroad'],axis=1)
y=data['TravelInsurance']

In [234]:
x

Unnamed: 0  Age  AnnualIncome  FamilyMembers  ChronicDiseases
0              0   31        400000              6                1
1              1   31       1250000              7                0
2              2   34        500000              4                1
3              3   28        700000              3                1
4              4   28        700000              8                1
...          ...  ...           ...            ...              ...
1982        1982   33       1500000              4                0
1983        1983   28       1750000              5                1
1984        1984   28       1150000              6                1
1985        1985   34       1000000              6                0
1986        1986   34        500000              4                0

[1987 rows x 5 columns]

In [235]:
y

0       0
1       0
2       1
3       0
4       0
       ..
1982    1
1983    0
1984    0
1985    1
1986    0
Name: TravelInsurance, Length: 1987, dtype: int64

In [236]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [237]:
Standard_x=scaler.fit_transform(x)
Standard_x

array([[-1.73117934,  0.4634296 , -1.41406139,  0.77496371,  1.6123392 ],
       [-1.72943595,  0.4634296 ,  0.84201171,  1.39637327, -0.62021689],
       [-1.72769257,  1.49344596, -1.14864102, -0.46785541,  1.6123392 ],
       ...,
       [ 1.72769257, -0.56658675,  0.57659134,  0.77496371,  1.6123392 ],
       [ 1.72943595,  1.49344596,  0.1784608 ,  0.77496371, -0.62021689],
       [ 1.73117934,  1.49344596, -1.14864102, -0.46785541, -0.62021689]])

In [238]:
x=Standard_x

In [239]:
x

array([[-1.73117934,  0.4634296 , -1.41406139,  0.77496371,  1.6123392 ],
       [-1.72943595,  0.4634296 ,  0.84201171,  1.39637327, -0.62021689],
       [-1.72769257,  1.49344596, -1.14864102, -0.46785541,  1.6123392 ],
       ...,
       [ 1.72769257, -0.56658675,  0.57659134,  0.77496371,  1.6123392 ],
       [ 1.72943595,  1.49344596,  0.1784608 ,  0.77496371, -0.62021689],
       [ 1.73117934,  1.49344596, -1.14864102, -0.46785541, -0.62021689]])

In [240]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=1)

In [241]:
x.shape,x_train.shape,x_test.shape

((1987, 5), (1589, 5), (398, 5))

In [242]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report


In [243]:
model = LogisticRegression()

In [244]:
model.fit(x_train,y_train)

LogisticRegression()

In [245]:
x_train_prediction_logistic = model.predict(x_train)
train_data_accuracy_logistic = accuracy_score(x_train_prediction_logistic,y_train)

In [246]:
train_data_accuracy_logistic

0.7482693517935809

In [247]:
x_test_prediction_logistic = model.predict(x_test)
test_data_accuracy_logistic = accuracy_score(x_test_prediction_logistic,y_test)

In [248]:
test_data_accuracy_logistic

0.7587939698492462

In [249]:
# Random forest classifier

from sklearn.ensemble import RandomForestClassifier


In [250]:
random_model = RandomForestClassifier()

In [251]:
random_model.fit(x_train,y_train)


RandomForestClassifier()

In [252]:
x_train_prediction_random = random_model.predict(x_train)
train_data_accuracy_random = accuracy_score(x_train_prediction_random,y_train)

In [253]:
train_data_accuracy_random

1.0

In [254]:
x_test_prediction_random = random_model.predict(x_test)
test_data_accuracy_random = accuracy_score(x_test_prediction_random,y_test)

In [255]:
test_data_accuracy_random

0.8190954773869347

In [256]:
# Naive Bayes

from sklearn.naive_bayes import GaussianNB

In [257]:
model1 = GaussianNB()

In [258]:
model1.fit(x_train,y_train)

GaussianNB()

In [259]:
x_train_prediction_Gaussian = model1.predict(x_train)
train_data_accuaracy_Gaussian = accuracy_score(x_train_prediction_Gaussian,y_train)

In [260]:
train_data_accuaracy_Gaussian

0.7646318439269981

In [261]:
x_test_prediction_Gaussian = model1.predict(x_test)
test_data_accuracy_Gaussian = accuracy_score(x_test_prediction_Gaussian,y_test)

In [262]:
test_data_accuracy_Gaussian

0.7587939698492462

In [263]:
confusion_matrix(y_test,x_test_prediction_Gaussian)



array([[226,  27],
       [ 69,  76]], dtype=int64)

In [264]:
print(classification_report(y_test,x_test_prediction_Gaussian))

              precision    recall  f1-score   support

           0       0.77      0.89      0.82       253
           1       0.74      0.52      0.61       145

    accuracy                           0.76       398
   macro avg       0.75      0.71      0.72       398
weighted avg       0.76      0.76      0.75       398

